name: Deploy Node.js to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: SSH Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_KEY }}
          script: |
            cd /home/adam/The-Hack-2025-08-TaniPintar-BE
            git pull origin main
            npm install
            npx prisma migrate dev
            pm2 restart TaniPintar
